services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - blog_pg_data:/var/lib/postgresql/data

volumes:
  blog_pg_data: